### ISSUE TITLE
Problem of the reply log initialization tangram

### ISSUE THREAD

**Issue by JeanDidier** [insilichem/tangram#10]
Hi, 

a minor point, the reply log of on MacOs gives the following:
Error fixing styles: <type 'exceptions.KeyError'> <class Tkinter.Frame at 0x104c06188>
! Could not obtain version info from https://api.github.com/repos/insilichem/tangram_mmsetup/releases/latest
  Reason: HTTP Error 404: Not Found

**Comment by jaimergp** [comment]
Yep, those are silent while we are in alpha stage. I have them there for debugging purposes, but can be ignored safely.

**Comment by JeanDidier** [comment]
OK, That I guessed. But to be sure....

Thank you!
